import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    FilePlus,
    FilePlus2,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    Sun,
    Trash,
    Twitter,
    User,
    X,
    LayoutDashboard,
    Users,
    Stethoscope,
    Calendar,
    UserCog,
    CalendarCheck,
    CalendarDays,
    Microscope,
    Pill,
    ClipboardCheck,
    LogOut,
    MessageSquare,
    CalendarPlus,
    MoreHorizontal,
    UserPlus,
    Home,
    FlaskConical,
    Search,
    Flame,
    PlusSquare,
    Clock,
    Activity,
    ShieldCheck,
    Filter,
    Download,
    FileDown,
    Edit,
    Eye,
    List,
    MapPin,
    DollarSign,
    Phone,
    Video,
    Send,
    Hospital
} from "lucide-react"

export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: Sun,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    layoutDashboard: LayoutDashboard,
    users: Users,
    stethoscope: Stethoscope,
    calendar: Calendar,
    userCog: UserCog,
    calendarCheck: CalendarCheck,
    calendarDays: CalendarDays,
    microscope: Microscope,
    pill: Pill,
    clipboardCheck: ClipboardCheck,
    creditCard: CreditCard,
    logOut: LogOut,
    messageSquare: MessageSquare,
    fileText: FileText,
    calendarPlus: CalendarPlus,
    moreHorizontal: MoreHorizontal,
    filePlus: FilePlus,
    filePlus2: FilePlus2,
    plus: Plus,
    userPlus: UserPlus,
    home: Home,
    hospital: Hospital,
    flaskConical: FlaskConical,
    search: Search,
    flame: Flame,
    plusSquare: PlusSquare,
    clock: Clock,
    activity: Activity,
    shieldCheck: ShieldCheck,
    filter: Filter,
    download: Download,
    fileDown: FileDown,
    edit: Edit,
    eye: Eye,
    list: List,
    mapPin: MapPin,
    dollarSign: DollarSign,
    phone: Phone,
    video: Video,
    moreVertical: MoreVertical,
    send: Send
}
