"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"
import { Badge } from "@/components/ui/badge"
import { format } from "date-fns"
import { jsPDF } from "jspdf"
import { toast } from "sonner"

export default function ReceptionistReportsPage() {
    const [stats, setStats] = useState({
        revenue: 0,
        newPatients: 0,
        appointments: 0,
        pendingBills: 0
    })
    const [transactions, setTransactions] = useState<any[]>([])
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        const fetchData = async () => {
            try {
                // Fetch Stats
                const statsRes = await fetch('/api/dashboard/stats')
                const statsData = await statsRes.json()

                // Fetch Transactions (Invoices)
                const billingRes = await fetch('/api/billing')
                const billingData = await billingRes.json()

                setStats({
                    revenue: statsData.revenue || 0,
                    newPatients: statsData.patients || 0, // Using total patients as proxy for now
                    appointments: statsData.appointmentsToday || 0,
                    pendingBills: statsData.billing || 0
                })
                setTransactions(billingData.slice(0, 5)) // Get latest 5
            } catch (error) {
                console.error("Failed to fetch report data", error)
                toast.error("Failed to load report data")
            } finally {
                setLoading(false)
            }
        }
        fetchData()
    }, [])

    const handleDownload = () => {
        try {
            // Check if jsPDF constructor is available
            const jsPDFConstructor = jsPDF as unknown as new () => any;
            const doc = new jsPDFConstructor();

            const today = format(new Date(), "MMMM dd, yyyy")

            // Header
            doc.setFontSize(22)
            doc.setTextColor(220, 38, 38) // Red-600
            doc.text("Daily Hospital Report", 20, 20)

            doc.setFontSize(12)
            doc.setTextColor(100)
            doc.text(`Date: ${today}`, 20, 30)
            doc.text(`Generated by: Receptionist Desk`, 20, 36)

            // Stats
            doc.setDrawColor(220, 38, 38)
            doc.line(20, 45, 190, 45)

            doc.setFontSize(16)
            doc.setTextColor(0)
            doc.text("Overview", 20, 55)

            doc.setFontSize(12)
            doc.text(`Total Revenue: ETB ${stats.revenue.toLocaleString()}`, 20, 65)
            doc.text(`Appointments Today: ${stats.appointments}`, 20, 72)
            doc.text(`New Patients: ${stats.newPatients}`, 110, 65)
            doc.text(`Pending Bills: ${stats.pendingBills}`, 110, 72)

            // Transactions
            doc.line(20, 85, 190, 85)
            doc.setFontSize(16)
            doc.text("Recent Transactions", 20, 95)

            let yPos = 110
            doc.setFontSize(10)
            doc.setTextColor(100)
            doc.text("Patient", 20, 105)
            doc.text("Service", 70, 105)
            doc.text("Status", 130, 105)
            doc.text("Amount", 170, 105)

            doc.setTextColor(0)
            transactions.forEach((tx) => {
                if (yPos > 270) {
                    doc.addPage()
                    yPos = 20
                }
                doc.text(tx.patient_name || "Unknown", 20, yPos)
                doc.text(tx.type || "General", 70, yPos)
                doc.text(tx.status || "Pending", 130, yPos)
                doc.text(`ETB ${parseFloat(tx.total).toLocaleString()}`, 170, yPos)
                yPos += 10
            })

            doc.save(`daily-report-${format(new Date(), "yyyy-MM-dd")}.pdf`)
            toast.success("Report downloaded successfully")
        } catch (error) {
            console.error("Download failed:", error)
            toast.error("Failed to generate PDF report")
        }
    }

    const statCards = [
        { title: "Total Revenue", value: `ETB ${stats.revenue.toLocaleString()}`, icon: <Icons.creditCard />, delta: "Today" },
        { title: "Active Patients", value: stats.newPatients.toString(), icon: <Icons.userPlus />, delta: "Total" },
        { title: "Appointments", value: stats.appointments.toString(), icon: <Icons.calendar />, delta: "Today" },
        { title: "Invoices", value: stats.pendingBills.toString(), icon: <Icons.fileText />, delta: "Total" },
    ]

    return (
        <div className="space-y-8 max-w-[1600px] mx-auto pb-10">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 bg-white p-8 rounded-3xl shadow-xl border border-red-50">
                <div>
                    <h1 className="text-4xl font-black tracking-tight text-gray-900">Daily Reports</h1>
                    <p className="text-lg font-medium text-muted-foreground mt-2">
                        Summary of today's <span className="text-red-600 font-bold">financials and operations</span>.
                    </p>
                </div>
                <Button
                    onClick={handleDownload}
                    disabled={loading}
                    className="bg-red-600 text-white hover:bg-red-700 font-black h-14 px-8 rounded-2xl shadow-xl shadow-red-200 transition-all hover:scale-105 active:scale-95 group"
                >
                    <Icons.download className="mr-3 h-5 w-5 transition-transform group-hover:-translate-y-1" />
                    Download Daily Summary
                </Button>
            </div>

            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
                {statCards.map((stat, i) => (
                    <Card key={i} className="group border-none shadow-xl transition-all duration-300 hover:shadow-2xl hover:scale-[1.03] border-l-4 border-l-red-600 bg-white relative overflow-hidden">
                        <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                            <CardTitle className="text-sm font-black uppercase tracking-widest text-red-900/60">{stat.title}</CardTitle>
                            <div className="p-2 rounded-lg bg-red-50 text-red-600 group-hover:bg-red-600 group-hover:text-white transition-all">
                                {stat.icon}
                            </div>
                        </CardHeader>
                        <CardContent>
                            <div className="text-3xl font-black tracking-tight text-gray-900">{stat.value}</div>
                            <div className="flex items-center gap-2 mt-2">
                                <Badge variant="secondary" className="bg-green-50 text-green-700 border-green-100 font-bold">{stat.delta}</Badge>
                                <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Since Shift Start</span>
                            </div>
                        </CardContent>
                    </Card>
                ))}
            </div>

            <Card className="border-none shadow-2xl overflow-hidden bg-white">
                <CardHeader className="bg-red-600 p-8">
                    <h3 className="text-xl font-black text-white uppercase tracking-widest">Recent Transactions</h3>
                </CardHeader>
                <CardContent className="p-0">
                    {loading ? (
                        <div className="p-12 text-center text-muted-foreground">Loading transactions...</div>
                    ) : transactions.length === 0 ? (
                        <div className="p-12 text-center text-muted-foreground">No transactions found for today.</div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="w-full border-collapse">
                                <thead className="bg-red-50/50">
                                    <tr>
                                        <th className="text-left py-4 px-6 text-xs font-bold text-red-800 uppercase tracking-widest">Patient</th>
                                        <th className="text-left py-4 px-6 text-xs font-bold text-red-800 uppercase tracking-widest">Service</th>
                                        <th className="text-left py-4 px-6 text-xs font-bold text-red-800 uppercase tracking-widest">Date</th>
                                        <th className="text-left py-4 px-6 text-xs font-bold text-red-800 uppercase tracking-widest">Status</th>
                                        <th className="text-right py-4 px-6 text-xs font-bold text-red-800 uppercase tracking-widest">Amount</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100">
                                    {transactions.map((tx) => (
                                        <tr key={tx.id} className="hover:bg-red-50/30 transition-colors">
                                            <td className="py-4 px-6 font-bold text-gray-900">{tx.patient_name}</td>
                                            <td className="py-4 px-6 text-sm text-gray-600 font-medium">{tx.type || 'General Service'}</td>
                                            <td className="py-4 px-6 text-sm text-gray-500 font-mono">{format(new Date(tx.date), 'MMM dd')}</td>
                                            <td className="py-4 px-6">
                                                <Badge className={tx.status === 'paid' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}>
                                                    {tx.status}
                                                </Badge>
                                            </td>
                                            <td className="py-4 px-6 text-right font-black text-gray-900">
                                                ETB {parseFloat(tx.total).toLocaleString()}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    )
}
